export const products = [
  {
    id: 'asus-vivobook-15',
    name: 'Vivobook 15 OLED',
    category: 'Laptops',
    brand: 'ASUS',
    price: 62990,
    originalPrice: 69990,
    rating: 4.7,
    reviews: 284,
    badge: 'BEST FOR WORK',
    description: 'A vivid OLED display and smooth performance for long workdays.',
    features: ['Intel Core i5', '16GB RAM', '512GB SSD', 'OLED display'],
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=85',
  },
  {
    id: 'macbook-air-m3',
    name: 'MacBook Air 13',
    category: 'Laptops',
    brand: 'Apple',
    price: 99900,
    originalPrice: 109900,
    rating: 4.9,
    reviews: 512,
    badge: 'EDITOR PICK',
    description: 'Quiet, all-day portability with a bright Liquid Retina display.',
    features: ['Apple M3', '16GB unified memory', '512GB SSD', '18-hour battery'],
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=85',
  },
  {
    id: 'pixel-9-pro',
    name: 'Pixel 9 Pro',
    category: 'Phones',
    brand: 'Google',
    price: 99999,
    originalPrice: 109999,
    rating: 4.8,
    reviews: 196,
    badge: 'GREAT CAMERA',
    description: 'Thoughtful AI tools meet a stunning camera and a bright display.',
    features: ['Tensor G4', '16GB RAM', '50MP camera', '7-year updates'],
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=900&q=85',
  },
  {
    id: 'samsung-s24',
    name: 'Galaxy S24',
    category: 'Phones',
    brand: 'Samsung',
    price: 74999,
    originalPrice: 89999,
    rating: 4.6,
    reviews: 438,
    badge: 'POPULAR',
    description: 'A compact flagship with a crisp screen and versatile cameras.',
    features: ['Snapdragon 8 Gen 3', '8GB RAM', '50MP camera', '120Hz display'],
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=85',
  },
  {
    id: 'sony-wh1000xm5',
    name: 'WH-1000XM5',
    category: 'Audio',
    brand: 'Sony',
    price: 29990,
    originalPrice: 34990,
    rating: 4.8,
    reviews: 621,
    badge: 'TRAVEL FAVOURITE',
    description: 'Soft over-ear comfort and quiet listening wherever you go.',
    features: ['Noise cancelling', '30-hour battery', 'Multipoint', 'Fast charge'],
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85',
  },
  {
    id: 'jbl-live-770nc',
    name: 'Live 770NC',
    category: 'Audio',
    brand: 'JBL',
    price: 8999,
    originalPrice: 12999,
    rating: 4.5,
    reviews: 183,
    badge: 'UNDER ₹10K',
    description: 'Big, lively sound with adaptive noise cancelling for less.',
    features: ['Adaptive ANC', '65-hour battery', 'Spatial sound', 'Voice aware'],
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=85',
  },
  {
    id: 'apple-watch-series-10',
    name: 'Watch Series 10',
    category: 'Wearables',
    brand: 'Apple',
    price: 46900,
    originalPrice: 49900,
    rating: 4.7,
    reviews: 154,
    badge: 'NEW ARRIVAL',
    description: 'A thinner everyday companion for health, fitness and quick calls.',
    features: ['Always-on OLED', 'ECG app', 'Water resistant', 'Fast charging'],
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=85',
  },
  {
    id: 'garmin-forerunner-265',
    name: 'Forerunner 265',
    category: 'Wearables',
    brand: 'Garmin',
    price: 41990,
    originalPrice: 44990,
    rating: 4.8,
    reviews: 207,
    badge: 'FOR RUNNERS',
    description: 'Bright training insights and reliable GPS for your next run.',
    features: ['AMOLED display', 'GPS', 'Training readiness', '13-day battery'],
    image: 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?auto=format&fit=crop&w=900&q=85',
  },
  {
    id: 'logitech-mx-keys-s',
    name: 'MX Keys S',
    category: 'Accessories',
    brand: 'Logitech',
    price: 10995,
    originalPrice: 12995,
    rating: 4.6,
    reviews: 321,
    badge: 'DESK UPGRADE',
    description: 'A precise, comfortable wireless keyboard for a considered desk.',
    features: ['Low-profile keys', 'Backlit', 'Bluetooth', 'USB-C rechargeable'],
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=85',
  },
  {
    id: 'adidas-supernova-rise',
    name: 'Supernova Rise',
    category: 'Shoes',
    brand: 'Adidas',
    price: 10999,
    originalPrice: 13999,
    rating: 4.6,
    reviews: 146,
    badge: 'DAILY RUNNER',
    description: 'A cushioned, steady daily trainer for easy miles and errands.',
    features: ['Dreamstrike+ cushioning', 'Road running', 'Lightweight mesh', 'Rubber outsole'],
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85',
  },
]
